import { AppNotification } from "../models";

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "flash-g502",
    category: "offers",
    preferenceId: "flash",
    icon: "zap",
    title: "Oferta relâmpago: Logitech G502",
    description:
      "O mouse Logitech G502 HERO está por R$ 249,90, com 42% OFF na Kabum.",
    time: "Agora mesmo",
    createdAt: "2026-06-11T08:28:00-03:00",
    read: false,
    action: "product",
    offerId: 5,
  },
  {
    id: "coupon-kabum-peripherals",
    category: "coupons",
    preferenceId: "coupons",
    icon: "ticket-percent",
    title: "Novo cupom para periféricos",
    description:
      "Use PERIFA12 e ganhe 12% OFF em periféricos selecionados na Kabum.",
    time: "Há 4 minutos",
    createdAt: "2026-06-11T08:24:00-03:00",
    read: false,
    action: "coupon",
    offerId: 101,
    couponCode: "PERIFA12",
  },
  {
    id: "price-monitor-ultrawide",
    category: "offers",
    preferenceId: "priceDrops",
    icon: "trending-down",
    title: "Monitor atingiu o menor preço",
    description:
      "O Monitor Gamer UltraWide 34” caiu de R$ 3.299,90 para R$ 2.499,90.",
    time: "Há 18 minutos",
    createdAt: "2026-06-11T08:10:00-03:00",
    read: false,
    action: "product",
    offerId: 2,
  },
  {
    id: "coupon-steam-selected-games",
    category: "coupons",
    preferenceId: "coupons",
    icon: "badge-percent",
    title: "15% OFF em jogos selecionados",
    description:
      "O cupom STEAM15 foi confirmado pela comunidade e está ativo na Steam.",
    time: "Há 32 minutos",
    createdAt: "2026-06-11T07:56:00-03:00",
    read: false,
    action: "coupon",
    offerId: 1,
    couponCode: "STEAM15",
  },
  {
    id: "favorite-ps5-discount",
    category: "favorites",
    preferenceId: "discounts",
    icon: "heart",
    title: "Seu favorito recebeu desconto",
    description:
      "O PlayStation 5 Slim Digital agora está por R$ 3.499,90 na Amazon.",
    time: "Há 48 minutos",
    createdAt: "2026-06-11T07:40:00-03:00",
    read: false,
    action: "product",
    offerId: 11,
  },
  {
    id: "coupon-amazon-console-expiring",
    category: "coupons",
    preferenceId: "coupons",
    icon: "clock",
    title: "Cupom para consoles expira hoje",
    description:
      "O cupom CONSOLE10 oferece 10% OFF em consoles e acessórios elegíveis.",
    time: "Há 1 hora",
    createdAt: "2026-06-11T07:28:00-03:00",
    read: false,
    action: "coupon",
    offerId: 102,
    couponCode: "CONSOLE10",
  },
  {
    id: "stock-switch-oled",
    category: "favorites",
    preferenceId: "discounts",
    icon: "package-check",
    title: "Nintendo Switch OLED voltou ao estoque",
    description:
      "A versão branca voltou ao estoque por R$ 2.199,90. A disponibilidade pode acabar rápido.",
    time: "Há 1 hora",
    createdAt: "2026-06-11T07:05:00-03:00",
    read: false,
    action: "product",
    offerId: 12,
  },
  {
    id: "reply-monitor-community",
    category: "community",
    preferenceId: "community",
    icon: "message-circle",
    title: "Responderam seu comentário",
    description:
      "PixelStorm respondeu sua dúvida sobre garantia do monitor UltraWide.",
    time: "Há 2 horas",
    createdAt: "2026-06-11T06:18:00-03:00",
    read: false,
    action: "product",
    offerId: 2,
  },
  {
    id: "coupon-gpu-confirmed",
    category: "coupons",
    preferenceId: "coupons",
    icon: "ticket-percent",
    title: "Cupom confirmado para placas de vídeo",
    description:
      "GPU8OFF oferece 8% OFF em placas de vídeo selecionadas na Kabum.",
    time: "Há 2 horas",
    createdAt: "2026-06-11T06:02:00-03:00",
    read: false,
    action: "coupon",
    offerId: 104,
    couponCode: "GPU8OFF",
  },
  {
    id: "price-rtx4060",
    category: "offers",
    preferenceId: "priceDrops",
    icon: "trending-down",
    title: "RTX 4060 caiu para R$ 1.999,90",
    description:
      "A placa de vídeo GeForce RTX 4060 está R$ 500,00 abaixo do preço anterior.",
    time: "Há 3 horas",
    createdAt: "2026-06-11T05:15:00-03:00",
    read: false,
    action: "product",
    offerId: 9,
  },
  {
    id: "flash-ssd-kingston",
    category: "offers",
    preferenceId: "flash",
    icon: "zap",
    title: "SSD Kingston 1TB em oferta",
    description:
      "O SSD Kingston NV2 1TB está por R$ 329,90 na Amazon por tempo limitado.",
    time: "Há 3 horas",
    createdAt: "2026-06-11T04:52:00-03:00",
    read: false,
    action: "product",
    offerId: 8,
  },
  {
    id: "coupon-ssd-amazon",
    category: "coupons",
    preferenceId: "coupons",
    icon: "badge-percent",
    title: "Cupom para SSDs e armazenamento",
    description:
      "Aplique SSD15OFF para obter 15% OFF em armazenamento selecionado.",
    time: "Há 4 horas",
    createdAt: "2026-06-11T04:10:00-03:00",
    read: false,
    action: "coupon",
    offerId: 110,
    couponCode: "SSD15OFF",
  },
  {
    id: "favorite-headset-lower-price",
    category: "favorites",
    preferenceId: "discounts",
    icon: "heart",
    title: "Headset salvo ficou mais barato",
    description:
      "O HyperX Cloud III caiu para R$ 479,90, com 31% de desconto.",
    time: "Há 5 horas",
    createdAt: "2026-06-11T03:22:00-03:00",
    read: false,
    action: "product",
    offerId: 6,
  },
  {
    id: "community-like-publication",
    category: "community",
    preferenceId: "community",
    icon: "heart",
    title: "Sua publicação recebeu novas curtidas",
    description:
      "Mais usuários marcaram a oferta do Logitech G502 como um bom drop.",
    time: "Há 6 horas",
    createdAt: "2026-06-11T02:30:00-03:00",
    read: true,
    action: "product",
    offerId: 5,
  },
  {
    id: "coupon-rgb-aliexpress",
    category: "coupons",
    preferenceId: "coupons",
    icon: "ticket-percent",
    title: "22% OFF em acessórios RGB",
    description:
      "O cupom RGB22 está disponível para iluminação, fans e acessórios selecionados.",
    time: "Há 8 horas",
    createdAt: "2026-06-11T00:18:00-03:00",
    read: true,
    action: "coupon",
    offerId: 111,
    couponCode: "RGB22",
  },
  {
    id: "price-lenovo-loq",
    category: "offers",
    preferenceId: "priceDrops",
    icon: "trending-down",
    title: "Notebook gamer abaixo de R$ 5 mil",
    description:
      "O Lenovo LOQ com RTX 4050 caiu para R$ 4.999,90 na Amazon.",
    time: "Ontem",
    createdAt: "2026-06-10T20:40:00-03:00",
    read: true,
    action: "product",
    offerId: 21,
  },
  {
    id: "coupon-epic-rpg",
    category: "coupons",
    preferenceId: "coupons",
    icon: "badge-percent",
    title: "25% OFF em RPGs na Epic",
    description:
      "Use RPG25 em títulos participantes durante a campanha atual.",
    time: "Ontem",
    createdAt: "2026-06-10T18:15:00-03:00",
    read: true,
    action: "coupon",
    offerId: 114,
    couponCode: "RPG25",
  },
  {
    id: "stock-corsair-memory",
    category: "favorites",
    preferenceId: "discounts",
    icon: "package-check",
    title: "Memória Corsair DDR5 disponível novamente",
    description:
      "O kit Corsair Vengeance RGB 32GB voltou ao estoque por R$ 749,90.",
    time: "Ontem",
    createdAt: "2026-06-10T15:45:00-03:00",
    read: true,
    action: "product",
    offerId: 16,
  },
  {
    id: "system-notification-preferences",
    category: "system",
    preferenceId: "platform",
    icon: "bell",
    title: "Controle melhor o seu radar",
    description:
      "Escolha no perfil quais alertas de preço, cupons e comunidade deseja receber.",
    time: "Há 2 dias",
    createdAt: "2026-06-09T14:00:00-03:00",
    read: true,
    action: "profile",
  },
  {
    id: "system-publication-review",
    category: "system",
    preferenceId: "platform",
    icon: "check-check",
    title: "Moderação de publicações atualizada",
    description:
      "Agora você acompanha o status das suas publicações diretamente no perfil.",
    time: "Há 3 dias",
    createdAt: "2026-06-08T11:30:00-03:00",
    read: true,
    action: "profile",
  },
];
