import { AppNotification } from "../models";

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "flash-g502",
    category: "offers",
    preferenceId: "flash",
    icon: "zap",
    title: "Oferta relâmpago",
    description: "Mouse Logitech G502 com 42% OFF.",
    time: "Agora mesmo",
    createdAt: "2026-06-09T18:30:00-03:00",
    read: false,
    action: "offer",
    offerId: 2,
  },
  {
    id: "coupon-kabum",
    category: "coupons",
    preferenceId: "coupons",
    icon: "ticket-percent",
    title: "Novo cupom da Kabum",
    description: "Cupom CYBER10 garante 10% OFF em periféricos.",
    time: "Há 5 minutos",
    createdAt: "2026-06-09T18:25:00-03:00",
    read: false,
    action: "coupon",
    offerId: 2,
    couponCode: "CYBER10",
  },
  {
    id: "price-monitor",
    category: "offers",
    preferenceId: "priceDrops",
    icon: "trending-down",
    title: "Preço caiu",
    description: "Monitor Gamer LG UltraGear 144Hz caiu para R$ 899,90.",
    time: "Há 2 horas",
    createdAt: "2026-06-09T16:30:00-03:00",
    read: false,
    action: "product",
    offerId: 2,
  },
  {
    id: "favorite-cyberpunk",
    category: "favorites",
    preferenceId: "discounts",
    icon: "heart",
    title: "Favorito com desconto",
    description: "Cyberpunk 2077: Ultimate Edition recebeu 67% OFF.",
    time: "Há 3 horas",
    createdAt: "2026-06-09T15:30:00-03:00",
    read: false,
    action: "product",
    offerId: 1,
  },
  {
    id: "coupon-terabyte",
    category: "coupons",
    preferenceId: "coupons",
    icon: "clock",
    title: "Cupom expirando",
    description: "Seu cupom da Terabyte expira em 2 horas.",
    time: "Há 4 horas",
    createdAt: "2026-06-09T14:30:00-03:00",
    read: false,
    action: "coupon",
    offerId: 2,
    couponCode: "SETUP15",
  },
  {
    id: "reply-community",
    category: "community",
    preferenceId: "community",
    icon: "message-circle",
    title: "Nova resposta no seu comentário",
    description: "PixelStorm respondeu sua análise sobre o monitor gamer.",
    time: "Há 6 horas",
    createdAt: "2026-06-09T12:30:00-03:00",
    read: false,
    action: "offer",
    offerId: 2,
  },
  {
    id: "stock-favorite",
    category: "favorites",
    preferenceId: "discounts",
    icon: "package-check",
    title: "Favorito voltou ao estoque",
    description: "O monitor gamer que você salvou está disponível novamente.",
    time: "Ontem",
    createdAt: "2026-06-08T20:00:00-03:00",
    read: true,
    action: "product",
    offerId: 2,
  },
  {
    id: "system-update",
    category: "system",
    preferenceId: "platform",
    icon: "bell",
    title: "Novidade no CyberDrops",
    description:
      "Agora você pode acompanhar quedas de preço na Central de Notificações.",
    time: "Há 2 dias",
    createdAt: "2026-06-07T15:00:00-03:00",
    read: true,
    action: "profile",
  },
];
